language: node_js
node_js:
  - 'iojs'
  - '4.1'
before_script:
  - gem update --system
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install
  - 'cp app/scripts/configs/config.js{.default,}'
